apiVersion: v1
kind: ServiceAccount
metadata:
  name: pseudo-terminal-manager-account
  namespace: pseudo-terminals
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pseudo-terminal-manager-role
  namespace: pseudo-terminals
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "statefulsets"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pseudo-terminal-manager-binding
  namespace: pseudo-terminals
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pseudo-terminal-manager-role
subjects:
  - kind: ServiceAccount
    name: pseudo-terminal-manager-account
    namespace: pseudo-terminals
## cluster role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pseudo-terminal-manager-role
  namespace: pseudo-terminals
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pseudo-terminal-manager-binding
  namespace: pseudo-terminals
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pseudo-terminal-manager-role
subjects:
  - kind: ServiceAccount
    name: pseudo-terminal-manager-account
    namespace: pseudo-terminals
