# k -n ptys expose pod webserver-5f94d8f8d-tclwx --target-port=5252 --name=dev-web-npsvc --type='NodePort'
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: dev-web-npsvc
  namespace: ptys
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 5252
      protocol: TCP
      targetPort: 5252
  selector:
    app: webserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
