kind: Deployment
apiVersion: apps/v1
metadata:
  name: man-pty
  namespace: ptys
  labels:
    app: man-pty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: man-pty
  template:
    metadata:
      labels:
        app: man-pty
    spec:
      # man-pty-internal-svc.ptys.svc.cluster.local
      hostname: man-pty
      subdomain: p1
      serviceAccount: man-pty-account
      serviceAccountName: man-pty-account
      imagePullSecrets:
        - name: mdr
      containers:
        - name: man-pty
          image: registry.digitalocean.com/mdr/man-pty
          env:
            - name: GINPORT
              value: "6262"
          ports:
            - name: gin-api
              containerPort: 6262
          command: ["sleep"]
          args: ["infinity"]
---
apiVersion: v1
kind: Service
metadata:
  name: man-pty-internal-svc
  namespace: ptys
spec:
  selector:
    app: man-pty
  ports:
    - protocol: TCP
      port: 6262
      targetPort: 6262
