kind: Deployment
apiVersion: apps/v1
metadata:
  name: webserver
  namespace: pseudo-terminals
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      hostname: webserver
      subdomain: p1
      imagePullSecrets:
        - name: mdr
      containers:
        - name: webserver
          image: registry.digitalocean.com/mdr/wt-webserver
          env:
            - name: LISTENPORT
              value: "5252"
          ports:
            - name: listenport
              containerPort: 5252
          # command: ["node"]
          # args: ["/app/server.js"]
          command: ["sleep"]
          args: ["infinity"]
