kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ptys-set
  namespace: ptys
  labels:
    app: ptys-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ptys-set
  template:
    metadata:
      labels:
        app: ptys-set
    spec:
      containers:
        - name: ptys-set
          command: ["node"]
          args: ["/app/containerPTY.js"]
          image: registry.digitalocean.com/mdr/pty
          ports:
            - name: pty-port
              containerPort: 7070
