kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: pseudo-terminals-set
  namespace: pseudo-terminals
  labels:
    app: pseudo-terminals-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pseudo-terminals-set
  template:
    metadata:
      labels:
        app: pseudo-terminals-set
    spec:
      containers:
        - name: pseudo-terminal
          command: ["node"]
          args: ["/app/containerPseudoTerminal.js"]
          image: registry.digitalocean.com/mdr/pseudo-terminal
          ports:
            - name: pseudo-terminal-port
              containerPort: 7070
