imagePullSecrets:
  - name: ghcr-secret
nameOverride: ""
fullnameOverride: ""
webserver:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/england2/webterm-webserver
    pullPolicy: IfNotPresent
    tag: e8f1be174cbf555cdf711989aa52bb968618dc29
  command:
    - node
    - /app/server.js
  args: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  env: []
  resources: {}
  service:
    type: ClusterIP
    port: 5252
  testNodePort:
    enabled: true
    nodePort: 30052
  corsAllowOrigin: "*"
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  httpRoute:
    enabled: false
    annotations: {}
    parentRefs:
      - name: gateway
        sectionName: http
    hostnames:
      - chart-example.local
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
manager:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/england2/webterm-pseudo-terminal-manager
    pullPolicy: IfNotPresent
    tag: e8f1be174cbf555cdf711989aa52bb968618dc29
  command:
    - /app/pseudo-terminal-manager
  args: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  env: []
  resources: {}
  service:
    port: 6262
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""
  rbac:
    create: true
  nodeSelector: {}
  tolerations: []
  affinity: {}
terminals:
  enabled: true
  replicaCount: 3
  podManagementPolicy: OrderedReady
  image:
    repository: ghcr.io/england2/webterm-pseudo-terminal
    pullPolicy: IfNotPresent
    tag: e8f1be174cbf555cdf711989aa52bb968618dc29
  command: []
  args: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  env: []
  resources: {}
  containerPort: 7070
  nodeSelector: {}
  tolerations: []
  affinity: {}
