# compile man-pty
FROM golang:1.19.8
COPY man-pty/* ./
# RUN go mod tidy 
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o man-pty .

# build pod container
# TODO test alpine
FROM debian
EXPOSE 6262

WORKDIR /app
COPY start.sh .
COPY --from=0 man-pty .

CMD ["sh", "start.sh"]